sudo: false
language: python
python:
- 3.4
- 3.5
- 3.6
install:
- pip install tox-travis
script: tox
deploy:
  provider: pypi
  user: elviejokike
  password:
    secure: Gm+mkPNlz4UY8ij2swDlsBdjINH+fef3tlk/dgoeKjHurvFvc6c9CTJEftgKNc4jDF1PC6uqMZYhVWYMXbPyIaU1ROlqgfGnBQJDPcad2eNyN2MgBwOQu3b35BhTQ0wFbDT4Kom+8UZrijb7Rq6H2SJpWkVhGWZHJR0kc8WcfBUSnzwFl0GbNOPB9s2sdCvcG139DO1jGDXpfmM9W+wFATKPBR3AI5SjwoBGOEEmhwT0jaSCDTQzUNWv3uC0mCMMk180r18L3/09b7SZqkSGUgv3/nE0CYBN+1spaDomrzVm5KuHx3IbxKIUYSbnD9u4qndBkjwVM5oJfNkHmbE0UQABuk6tfw3R6gDAygZbcH6blRNXtbzSy+KtFqHXZsoxZu+xZygdA5oQZ3gL194BQ8x2v6Zpmf8WDe7iljxcwrlfEGsFm6mVkvzmdKhm2Uv71OrM7uPjgjDXCpRRJTdQyUdIl4a2w0wysZ7rC96XEf2iuwjb4QA7QHweDeyXixX2pS4CvfNmTmr00KqUzvn8dkSZshJ9mhpZKnnpWNs9/EkshKX0F15DBN88tDgyXqiyh/pCYpRkijSBYJn1dmlC3GcGhHb6HXpApdg8fKz4KNfmePb+q+jPuBYOLYEg7FElhRQ6dZMDUJC7bmN0acAyV/iwB9n3J5ZoNmtlgSIilvs=
  on:
    branch: master
    tags: true
    distributions: sdist bdist_wheel
    repo: elviejokike/awsspawner4jhub
